Frontend/Find-A-Tutor.Frontend/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Find_A_Tutor.Frontend.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Frontend/Find-A-Tutor.Frontend/Pages/Details.cshtml.cs
using System;
using System.Threading.Tasks;
using Find_A_Tutor.Frontend.Model;
using Find_A_Tutor.Frontend.Services;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;

namespace Find_A_Tutor.Frontend.Pages
{
    public class DetailsModel : PageModel
    {
        private readonly IPrivateLessonService _privateLessonService;
        public readonly string _payPalClientId;
        public Result<PrivateLesson> privateLesson;

        public DetailsModel(IPrivateLessonService privateLessonService, IConfiguration configuration)
        {
            _privateLessonService = privateLessonService;
            _payPalClientId = configuration.GetValue<string>("PayPal:client-id");
        }

        public async Task OnGet(Guid id)
        {
            if(id != Guid.Empty)
            {
                privateLesson = await _privateLessonService.Get(id);
            }else
            {
                Redirect("Student");
            }            
        }
    }
}

Frontend/Find-A-Tutor.Frontend/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Find_A_Tutor.Frontend.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Frontend/Find-A-Tutor.Frontend/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Find_A_Tutor.Frontend.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Frontend/Find-A-Tutor.Frontend/Pages/Login.cshtml.cs
using Find_A_Tutor.Frontend.Model;
using Find_A_Tutor.Frontend.Model.Account;
using Find_A_Tutor.Frontend.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Find_A_Tutor.Frontend.Pages
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public string Email { get; set; }
        [BindProperty]
        public string Password { get; set; }

        private readonly IAccountService _accountService;
        public Result<TokenDto> Token { get; set; }
        public List<string> Errors { get; set; }

        public LoginModel(IAccountService accountService)
        {
            _accountService = accountService;
            Errors = new List<string>();
        }
        public async Task OnPost()
        {
            var response = await _accountService.Login(Email, Password);

            if (response.IsSuccess)
            {
                var data = response.Value;

                HttpContext.Session.SetString("token", data.Token);
                HttpContext.Session.SetString("role", data.Role);

                if (data.Role == "student")
                {
                    Response.Redirect("Student");
                }
                if (data.Role == "tutor")
                {
                    Response.Redirect("Tutor");
                }
                if (data.Role == "admin")
                {
                    Response.Redirect("Index");
                }
            }
            else
            {
                Errors.AddRange(response.Errors);
            }
        }
    }
}

Frontend/Find-A-Tutor.Frontend/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Find_A_Tutor.Frontend.Pages
{
    public class LogoutModel : PageModel
    {
        public void OnGet()
        {
            HttpContext.Session.SetString("token", "");
            Response.Redirect("Index");
        }
    }
}

Frontend/Find-A-Tutor.Frontend/Pages/NewLesson.cshtml.cs
using Find_A_Tutor.Frontend.Model;
using Find_A_Tutor.Frontend.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Find_A_Tutor.Frontend.Pages
{
    public class NewLessonModel : PageModel
    {
        [BindProperty]
        public string Description { get; set; }
        [BindProperty]
        public string SelectedSubjectId { get; set; }
        [BindProperty]
        public DateTime RelevantTo { get; set; }
        [BindProperty]
        public double Time { get; set; }
        public List<SchoolSubject> SchoolSubjects { get; set; }

        public List<string> Messages { get; set; }
        private readonly IPrivateLessonService _privateLessonService;
        private readonly ISchoolSubjectService _schoolSubjectService;

        public NewLessonModel(IPrivateLessonService privateLessonService, ISchoolSubjectService schoolSubjectService)
        {
            _privateLessonService = privateLessonService;
            _schoolSubjectService = schoolSubjectService;
            Messages = new List<string>();
        }

        public async Task OnGet()
        {
            var token = HttpContext.Session.GetString("token");
            var role = HttpContext.Session.GetString("role");

            if (token == null && role == "student")
            {
                Response.Redirect("Student");
            }
            if (role == "tutor")
            {
                Response.Redirect("Tutor");
            }
            if (token == null)
            {
                Response.Redirect("Login");
            }

            await FetchSchoolSubjects();
        }

        public async Task OnPost()
        {
            await FetchSchoolSubjects();
            var subjectName = SchoolSubjects.Where(s => s.Id.ToString() == SelectedSubjectId);

            var response = await _privateLessonService.Post(new PrivateLesson
            {
                Description = Description,
                Subject = subjectName.FirstOrDefault().Name,
                RelevantTo = RelevantTo,
                Time = Time
            });

            if (response.IsSuccess)
            {
                Messages.Add("Announcement was added 😊");
            }
            else
            {
                Messages.AddRange(response.Errors);
            }
        }

        public async Task FetchSchoolSubjects()
        {
            var response = await _schoolSubjectService.GetAll();

            if (response.IsSuccess)
            {
                SchoolSubjects = response.Value.ToList();
            }
            else
            {
                Messages.AddRange(response.Errors);
            }
        }
    }
}

Frontend/Find-A-Tutor.Frontend/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Find_A_Tutor.Frontend.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Frontend/Find-A-Tutor.Frontend/Pages/Register.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Find_A_Tutor.Frontend.Model.Account;
using Find_A_Tutor.Frontend.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Find_A_Tutor.Frontend.Pages
{
    public class RegisterModel : PageModel
    {
        [BindProperty]
        public string FirstName { get; set; }
        [BindProperty]
        public string LastName { get; set; }
        [BindProperty]
        public string Email { get; set; }
        [BindProperty]
        public string Password { get; set; }
        [BindProperty]
        public bool IsTutor { get; set; }

        public List<string> Messages { get; set; }
        private readonly IAccountService _accountService;

        public RegisterModel(IAccountService accountService)
        {
            _accountService = accountService;
            Messages = new List<string>();
        }
        public async Task OnPost()
        {
            var response = await _accountService.Register(new Register
            {
                Email = Email,
                Password = Password,
                FirstName = FirstName,
                LastName = LastName,
                Role = IsTutor ? "tutor" : "student"
            });

            if (response.IsSuccess)
            {
                Messages.Add("Your account was created 😊");
            }
            else
            {
                Messages.AddRange(response.Errors);
            }
        }
    }
}

Frontend/Find-A-Tutor.Frontend/Pages/Student.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Find_A_Tutor.Frontend.Model;
using Find_A_Tutor.Frontend.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Find_A_Tutor.Frontend.Pages
{
    public class StudentModel : PageModel
    {
        private readonly IAccountService _accountService;
        public Result<IEnumerable<PrivateLesson>> privateLessons;
        public List<string> Messages;

        public StudentModel(IAccountService accountService)
        {
            _accountService = accountService;
            Messages = new List<string>();
        }

        public async Task OnGet()
        {
            var token = HttpContext.Session.GetString("token");
            var role = HttpContext.Session.GetString("role");

            if (token != null && role == "student")
            {
                privateLessons = await _accountService.GetLessonsForUser();
            }
            else if (role == "tutor")
            {
                Response.Redirect("Tutor");
            }
            else
            {
                Response.Redirect("Login");
            }
        }
    }
}

Frontend/Find-A-Tutor.Frontend/Pages/Take.cshtml.cs
using Find_A_Tutor.Frontend.Model;
using Find_A_Tutor.Frontend.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Find_A_Tutor.Frontend.Pages
{
    public class TakeModel : PageModel
    {
        private readonly IPrivateLessonService _privateLessonService;
        public Result<PrivateLesson> privateLesson;
        public List<string> Messages { get; set; }

        [BindProperty]
        public double PricePerHour { get; set; }

        public TakeModel(IPrivateLessonService privateLessonService)
        {
            _privateLessonService = privateLessonService;
            Messages = new List<string>();
        }
        public async Task OnGetAsync(Guid id)
        {
            if (id != Guid.Empty)
            {
                privateLesson = await _privateLessonService.Get(id);
            }
            else
            {
                Redirect("Tutor");
            }
        }

        public async Task OnPostAssignTutor(Guid id)
        {
            var result = await _privateLessonService.AssignTutor(new AssignTutor
            { 
                PricePerHour = PricePerHour,
                PrivateLessonId = id
            });

            if (result.IsSuccess)
            {
                Messages.Add("Announcement was assinged to your account 😊");
            }
            else
            {
                Messages.AddRange(result.Errors);
            }

            privateLesson = await _privateLessonService.Get(id);
        }
    }
}

Frontend/Find-A-Tutor.Frontend/Pages/Tutor.cshtml.cs
using Find_A_Tutor.Frontend.Model;
using Find_A_Tutor.Frontend.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Find_A_Tutor.Frontend.Pages
{
    public class TutorModel : PageModel
    {
        private readonly IPrivateLessonService _privateLessonService;
        public Result<IEnumerable<PrivateLesson>> privateLessons;
        public List<string> Messages { get; set; }

        public TutorModel(IPrivateLessonService privateLessonService)
        {
            _privateLessonService = privateLessonService;
            Messages = new List<string>();
        }

        public async Task OnGet()
        {
            var token = HttpContext.Session.GetString("token");
            var role = HttpContext.Session.GetString("role");

            if (token != null && role == "tutor")
            {
                privateLessons = await _privateLessonService.GetAll();
            }
            else if (role == "student")
            {
                Response.Redirect("Student");
            }
            else
            {
                Response.Redirect("Login");
            }
        }

        public async Task OnGetRemoveAssignedTutor(Guid id)
        {
            var result = await _privateLessonService.RemoveAssignedTutor(id.ToString());
            privateLessons = await _privateLessonService.GetAll();

            if (result.IsSuccess)
            {
                Messages.Add("Announcement was removed from your account 😊");
            }
            else
            {
                Messages.AddRange(result.Errors);
            }
        }
    }
}

Frontend/Find-A-Tutor.Frontend/Pages/About.cshtml
@page
@model PrivacyModel
@{
    ViewData["Title"] = "About";
}
<h1>@ViewData["Title"]</h1>

<p>Find-A-Tutor is a simple student-tutor app to help student find a tutor for themselfs and to tutors find suited students for them.</p>

Frontend/Find-A-Tutor.Frontend/Pages/Details.cshtml
@page
@model Find_A_Tutor.Frontend.Pages.DetailsModel
@{
    ViewData["Title"] = "Details of announcement 📖";
}

<link rel="stylesheet" type="text/css" href="~/css/main.css">
<link rel="stylesheet" type="text/css" href="~/css/details.css">

<script src="https://www.paypal.com/sdk/js?client-id=@Model._payPalClientId&currency=PLN">
</script>

<div class="container">
    <div class="row">
        <div class="col-6">
            <h2>Details of announcement 📖</h2>
        </div>
        <div class="col-6">
            <a href="/Student">
                <p class="text-right">Go back to panel</p>
            </a>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12" style="overflow-x:auto;">
            @{
                if (Model.privateLesson.IsSuccess)
                {
                    var privateLesson = Model.privateLesson.Value;
                    <h5>Created At:</h5>
                    <p>@privateLesson.CreatedAt</p>
                    <h5>Taken At:</h5>
                    <p>@(privateLesson.TakenAt.HasValue ? privateLesson.TakenAt.ToString() : "-")</p>
                    <h5>Relevant To:</h5>
                    <p>@privateLesson.RelevantTo.Value.ToString("dd.MM.yyyy")</p>
                    <h5>Description:</h5>
                    @*<textarea name="comment" rows="3" required="">@privateLesson.Description</textarea>*@
                    <p>@privateLesson.Description</p>
                    <h5>Subject:</h5>
                    <p>@privateLesson.Subject</p>
                    <h5>Assigned?</h5>
                    <p>@(privateLesson.IsAssigned.Value ? "✔️" : "❌")</p>
                    <h5>Paid?</h5>
                    <p>@(privateLesson.IsPaid.Value ? "✔️" : "❌")</p>
                    <h5>Completed?</h5>
                    <p>@(privateLesson.IsDone.Value ? "✔️" : "❌")</p>
                    <h5>Time</h5>
                    <p>@privateLesson.Time</p>
                    if (privateLesson.IsAssigned.Value)
                    {
                        <h5>Price per hour</h5>
                        <p>@privateLesson.PricePerHour</p>
                        <h5>Total price</h5>
                        <p>@privateLesson.TotalPrice</p>
                        if (!privateLesson.IsPaid.Value)
                        {
                            <div id="paypal-button-container"></div>
                        }
                    }
                }
                else
                {
                    @foreach (var err in Model.privateLesson.Errors)
                    {
                        <p class="msg">@err</p>
                    }
                }
            }
        </div>
    </div>
</div>

@if (!Model.privateLesson.Value.IsPaid.Value)
{
    <script>
        paypal.Buttons({
            createOrder: function (data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: @Model.privateLesson.Value.TotalPrice
                        },
                        description: 'Private lesson',
                        currency: 'PLN'
                    }]
                });
            },
            onApprove: async function (data, actions) {
                return await actions.order.capture().then(function (details) {
                    return fetch('/pay', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'Access-Control-Allow-Origin': '*'
                        },
                        body: JSON.stringify({
                            orderID: data.orderID,
                            privateLessonId: '@Model.privateLesson.Value.Id'
                        })
                    });
                });
            }
        }).render('#paypal-button-container');
    </script>
}

Frontend/Find-A-Tutor.Frontend/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <h6>at Find-A-Tutor. Log in to start using the portal.</h6>
</div>

Frontend/Find-A-Tutor.Frontend/Pages/Login.cshtml
@page
@model Find_A_Tutor.Frontend.Pages.LoginModel
@{
    ViewData["Title"] = "Log in";
}

<link rel="stylesheet" type="text/css" href="~/css/login.css">

<div class="wrapper">
    <div class="container">
        <form class="form-signin" method="post">
            <h2 class="form-signin-heading">Log in</h2>
            <input type="text" class="form-control" name="email" placeholder="Email Address" required="" autofocus="" />
            <input type="password" class="form-control" name="password" placeholder="Password" required="" />
            <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
        </form>
        <p class="text-center">You do not have an account? <a href="/Register">Register now</a></p>
        @foreach (var msg in Model.Errors)
        {
            <p class="text-center">@msg</p>
        }
    </div>

</div>

Frontend/Find-A-Tutor.Frontend/Pages/Logout.cshtml
@page
@model Find_A_Tutor.Frontend.Pages.LogoutModel
@{
    ViewData["Title"] = "Logout";
}

<h1 style="text-align: center">Logging out...</h1>

Frontend/Find-A-Tutor.Frontend/Pages/NewLesson.cshtml
@page
@model Find_A_Tutor.Frontend.Pages.NewLessonModel
@{
    ViewData["Title"] = "Create new announcement ✒️";
}
<link rel="stylesheet" type="text/css" href="~/css/newLesson.css">
<link rel="stylesheet" type="text/css" href="~/css/main.css">

<div class="container">
    <div class="row">
        <div class="col-6">
            <h2>Create new announcement ✒️</h2>
        </div>
        <div class="col-6">
            <a href="/Student">
                <p class="text-right">Go back to student panel</p>
            </a>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12">
            <form method="post">
                <p>Description</p>
                <input type="text" name="description" placeholder="Opis" required="" />
                <p>Name of subject</p>
                @Html.DropDownListFor(m => m.SelectedSubjectId, new SelectList(Model.SchoolSubjects, "Id", "Name"), "-- Select Subject --", new { id="schoolSubjectsList", required = "required"})
                <p>Announcement is relevant to</p>
                <input type="date" name="relevantTo" required="" />
                <p>How much time do you need?</p>
                <input type="number" step="0.5" name="time" required="" />
                <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
            </form>
            @foreach(var msg in Model.Messages)
            {
                <h3 class="msg">@msg</h3>
            }
        </div>
    </div>

</div>

Frontend/Find-A-Tutor.Frontend/Pages/Register.cshtml
@page
@model Find_A_Tutor.Frontend.Pages.RegisterModel
@{
    ViewData["Title"] = "Register";
}
   
<link rel="stylesheet" type="text/css" href="~/css/register.css">

<main class="my-form">
    <div class="cotainer">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Register</div>
                    <div class="card-body">
                        <form name="register" method="post">
                            <div class="form-group row">
                                <label for="first-name" class="col-md-4 col-form-label text-md-right">First name</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control" name="FirstName" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="LastName" class="col-md-4 col-form-label text-md-right">Last name</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control" name="LastName" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email_address" class="col-md-4 col-form-label text-md-right">E-Mail</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control" name="Email" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>
                                <div class="col-md-6">
                                    <input type="password" class="form-control" name="Password" required>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">Are you a tutor?</label>
                                <div class="col-md-6">
                                    <label class="switch">
                                        <input type="checkbox" name="IsTutor" asp-for="IsTutor">
                                        <span class="slider round"></span>
                                    </label>
                                </div>
                            </div>

                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Register
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                @foreach (var msg in Model.Messages)
                {
                    <p class="msg">@msg</p>
                }
            </div>
        </div>
    </div>
</main>

Frontend/Find-A-Tutor.Frontend/Pages/Take.cshtml
@page
@model Find_A_Tutor.Frontend.Pages.TakeModel
@{
    ViewData["Title"] = "Take an announcement 📖";
}

<link rel="stylesheet" type="text/css" href="~/css/main.css">
<link rel="stylesheet" type="text/css" href="~/css/details.css">

<div class="container">
    <div class="row">
        <div class="col-6">
            <h2>Take an announcement 📖</h2>
        </div>
        <div class="col-6">
            <a href="/Tutor">
                <p class="text-right">Go back to panel</p>
            </a>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12" style="overflow-x:auto;">
            @{
                if (Model.privateLesson.IsSuccess)
                {
                    <form method="post">
                    @{
                        var privateLesson = Model.privateLesson.Value;
                        <h5>Created At:</h5>
                        <p>@privateLesson.CreatedAt</p>
                        <h5>Taken At:</h5>
                        <p>@(privateLesson.TakenAt.HasValue ? privateLesson.TakenAt.ToString() : "-")</p>
                        <h5>Relevant To:</h5>
                        <p>@privateLesson.RelevantTo.Value.ToString("dd.MM.yyyy")</p>
                        <h5>Description:</h5>
                        <!--<textarea name="comment" rows="3" required="">@privateLesson.Description</textarea>-->
                        <p>@privateLesson.Description</p>
                        <h5>Subject:</h5>
                        <p>@privateLesson.Subject</p>
                        <h5>Assigned?</h5>
                        <p>@(privateLesson.IsAssigned.Value ? "✔️" : "❌")</p>
                        <h5>Paid?</h5>
                        <p>@(privateLesson.IsPaid.Value ? "✔️" : "❌")</p>
                        <h5>Completed?</h5>
                        <p>@(privateLesson.IsDone.Value ? "✔️" : "❌")</p>
                        <h5>Time</h5>
                        <p>@privateLesson.Time</p>
                        <h5>Price per hour</h5>
                        if (privateLesson.IsAssigned.Value)
                        {                            
							<p>@privateLesson.PricePerHour</p>
                            <h5>Total price</h5>
                            <p>@privateLesson.TotalPrice</p>
                        }
                        else
                        {
                            <input asp-for="PricePerHour" name="PricePerHour"/>
                            <button asp-page-handler="AssignTutor" asp-route-id="@privateLesson.Id" type="submit" class="btn btn-lg btn-primary btn-block">Take!</button>
                        }
                    }
                    </form>
                }
                else
                {
                    @foreach (var err in Model.privateLesson.Errors)
                    {
                        <p class="msg">@err</p>
                    }
                    @foreach (var err in Model.Messages)
                    {
                        <p class="msg">@err</p>
                    }
                }
            }
        </div>
    </div>
</div>

Frontend/Find-A-Tutor.Frontend/Pages/Tutor.cshtml
@page
@model Find_A_Tutor.Frontend.Pages.TutorModel
@{
    ViewData["Title"] = "Tutor panel 👨‍🏫";
}

<link rel="stylesheet" type="text/css" href="~/css/main.css">

<div class="container">
    <div class="row">
        <div class="col-12">
            <h2>Tutor panel 👨‍🏫</h2>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12">
            @if (Model.privateLessons.Value.Count() > 0 && Model.privateLessons.IsSuccess)
            {
                <table>
                    <tr>
                        <th>CreatedAt</th>
                        <th>TakenAt</th>
                        <th>RelevantTo</th>
                        <th>Description</th>
                        <th>Subject</th>
                        <th>Assigned?</th>
                        <th>Paid?</th>
                        <th>Completed?</th>
                        <th>Take</th>
                        <th>Give back</th>
                    </tr>
                    @foreach (var item in Model.privateLessons.Value)
                    {
                        <tr>
                            <td>@item.CreatedAt.Value.ToString("dd.MM.yyyy")</td>
                            <td>@(item.TakenAt.HasValue ? item.TakenAt.Value.ToString("dd.MM.yyyy") : null)</td>
                            <td>@(item.RelevantTo.HasValue ? item.RelevantTo.Value.ToString("dd.MM.yyyy") : null)</td>
                            <td>@item.Description</td>
                            <td>@item.Subject</td>
                            <td>@(@item.IsAssigned.Value ? "✔️" : "❌")</td>
                            <td>@(@item.IsPaid.Value ? "✔️" : "❌")</td>
                            <td>@(@item.IsDone.Value ? "✔️" : "❌")</td>
                            <td><a asp-page="/Take" asp-route-Id="@item.Id">Take</a></td>
                            <td><a asp-page-handler="RemoveAssignedTutor" asp-route-id="@item.Id">Give back</a></td>
                        </tr>
                    }
                </table>
            }
            else
            {
                <p>No announcements</p>
            }
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            @foreach (var msg in Model.Messages)
            {
                <p class="msg">@msg</p>
            }
        </div>
    </div>
</div>